######################################################################
# Automatically generated by qmake (2.01a) lun. déc. 28 05:10:01 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

ICON = icone.icns
CONFIG += release

# Input
HEADERS += CDirCopy.h FenetrePrincipale.h FenetreProgression.h
SOURCES += CDirCopy.cpp FenetrePrincipale.cpp FenetreProgression.cpp main.cpp
