######################################################################
# Automatically generated by qmake (2.01a) lun. 28. déc. 01:23:13 2009
######################################################################

TEMPLATE = app
CONFIG += release
RC_FILE = ressources.rc
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CDirCopy.h FenetrePrincipale.h FenetreProgression.h
SOURCES += CDirCopy.cpp FenetrePrincipale.cpp FenetreProgression.cpp main.cpp
